services:
  db:
    image: postgres:16.4
    container_name: postgres_container
    restart: "unless-stopped"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      # example on how to run initial script
      # - ./migrations/000001_create_initial_tables.up.sql:/docker-entrypoint-initdb.d/db_init.sql
      - ./pg_data:/var/lib/postgresql/data

  server:
    depends_on: 
      - db 
    container_name: "server"
    build: . 
    ports: 
      - 3000:3000
    volumes:
      - .:/usr/src/app
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=root
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
    