version: "3.9"
services:
  testdb:
    image: postgres:16.4
    container_name: postgres_container
    restart: "unless-stopped"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5432

  service:
    container_name: testservice
    build:
      context: .
      dockerfile: test.dockerfile
    volumes:
      - .:/go/src/github.com/eddie023/byd
    environment:
      - DB_CONNECTION_URI="postgres://root:postgres@testdb:5433/postgres?sslmode=disable"\
      - DB_HOSTNAME=db
    depends_on:
      - db
